#!/usr/bin/env ruby
#^syntax detection

forge "http://forge.puppetlabs.com"

mod 'puppetlabs/haproxy'
mod 'puppetlabs/ntp'

mod 'admin',
   :git => 'https://github.com/eToro/puppet-admin',
   :ref => '0.1.0'
